# Generated by Django 4.0.6 on 2022-08-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Queue',
                'verbose_name_plural': 'Queues',
                'ordering': ['-created_at'],
            },
        ),
    ]
