# Generated by Django 4.0.6 on 2022-08-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_l', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queue',
            new_name='QueueL',
        ),
    ]
